# np.ones

In [1]:
#create an array filled with ones
import numpy as np
arr= np.ones(5,dtype=int)
print(arr)

[1 1 1 1 1]


In [2]:
import numpy as np
arr= np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


# np.empty

In [3]:
#creates an array without initializing its element
import numpy as np
arr= np.empty(5)
print(arr) 

[5.e-324 5.e-324 5.e-324 5.e-324 5.e-324]


In [4]:
import numpy as np
arr= np.empty(5)
arr[:]=[1,2,3,4,5]
print(arr)

[1. 2. 3. 4. 5.]


# np.full

In [5]:
#creates an array where every element has the same value,provided by the user
import numpy as np
arr= np.full((3,3),7)
print(arr) 

[[7 7 7]
 [7 7 7]
 [7 7 7]]


# np.eye()

In [6]:
#creates a identical like matrix where the main diagonal is 1 and all other element are 0
import numpy as np
arr= np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
import numpy as np
arr= np.eye(3,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


# np.identity

In [8]:
import numpy as np
arr= np.identity(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
