# Dtypes

In [2]:
import numpy as np
a= np.array([10,20,30,40,50])
print(a.dtype)

int64


In [3]:
b= np.array([1.5,2.5,3.5])
print(b.dtype)

float64


# Itemsize

In [4]:
#Memory size of each element in bytes
a= np.array([10,20,30,40,50])
print(a.itemsize)

8


# nbytes

In [5]:
#total memory used by the array in bytes
a= np.array([10,20,30,40,50])
print(a.nbytes)

40


# Automatic Databytes

In [6]:
import numpy as np
a= np.array([1,2,3.5,6,5.5])
print(a)
print(a.dtype)

[1.  2.  3.5 6.  5.5]
float64


# Zeros

In [7]:
import numpy as np
a=np.zeros([5])
print(a)

[0. 0. 0. 0. 0.]


# Integer Zeros

In [8]:
import numpy as np
arr=np.zeros(5,dtype=int)
print(arr)

[0 0 0 0 0]


In [9]:
#2d zeros
import numpy as np
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
