# Numpy (Numerical Python)

In [3]:
#marks= [10,20,30,40,50]
import numpy as np
print(np.__version__)

2.2.6


# Numpy array

In [5]:
import numpy as np
numbers=np.array([1,2,3,4,5])
print(numbers)
print(type(numbers))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# ndarray

In [6]:
# 0 dimensional array
zero_dimensional_array = np.array(42)
print(zero_dimensional_array)

42


In [ ]:
#1 dimensional array
one_dimensional_array = np.array([1,2,3,4,5])
print(one_dimensional_array)

[1 2 3 4 5]


In [9]:
# 2 dimensional array
two_dimensional_array = np.array([[1,2,3],[4,5,6]])
print(two_dimensional_array)

[[1 2 3]
 [4 5 6]]


In [ ]:
# 3 dimensional array
#collection of matrices
three_dimensional_array = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(three_dimensional_array)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# N-dim

In [13]:
import numpy as np
a= np.array([10,20,30,40,50])
print(a.ndim)

1


In [14]:
b = np.array([[1,2,3],[4,5,6]])
print(b.ndim)

2


In [15]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.ndim)

3


# Shape

In [16]:
a= np.array([10,20,30,40,50])
print(a.shape)


(5,)


In [17]:
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)


(2, 3)


In [18]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.shape)

(2, 2, 2)


# Size

In [ ]:
b=np.array([[1,2,3],[4,5,6]]) 
print(b.size)

6


In [20]:
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c.size)

8


# Dtypes

In [21]:
a= np.array([10,20,30,40,50])
print(a.dtype)

int64


In [22]:
b= np.array([1.5,2.5,3.5])
print(b.dtype)

float64


# Itemsize

In [23]:
#Memory size of each element in bytes
a= np.array([10,20,30,40,50])
print(a.itemsize)

8


nbytes

In [25]:
#total memory used by the array in bytes
a= np.array([10,20,30,40,50])
print(a.nbytes)

40
